# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20161106_0433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('age', models.IntegerField()),
                ('home_group', models.CharField(max_length=5)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'db_table': 'student_info',
            },
        ),
    ]
